data:
  file_path: "inputX_compressed.npz"
  min_samples: 10
  max_len: 1024
  max_freq: 2048

model:
  filters: [64, 32, 18, 8]
  bottleneck_dim: 64
  lr: 0.0001

train:
  pretrain_epochs: 50
  finetune_epochs: 30
  batch_size: 128
  beta_rep: 0.1
  target_ratio: 0.1
  update_centers: true
  update_interval: 5
  momentum: 0.5

cluster:
  n_clusters: 5

automl:
  n_trails: 5
  bottleneck_dim: [16, 32, 64]
  lr: [0.0001, 0.001, 0.01]
  beta_rep: [0.001, 0.01, 0.1]
  n_clusters: [3, 5, 7]
  filters:
    - [32, 16, 8, 4]
    - [64, 32, 16, 8]
    - [128, 64, 32, 16]